name: mdlmustache
version: 0.2.5

author: Greg Lowe <greg@vis.net.nz>
description: Mustache template library
homepage: https://github.com/xxgreg/mustache

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  reflectable: '^0.4.0'

  validate: ^1.0.0

dev_dependencies:
  test: any
  grinder: any

