name: 'reflection_test_browser2'

version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  intl: '^0.15.0'

  reflection_test_pkgref:
    path: /Volumes/Daten/DevLocal/DevDart/MdlMustache/samples/browser2/pkgref
        
#  mdlmustache:
#    path: ../../../

dev_dependencies:
  dart_to_js_script_rewriter: '^0.1.0'
  
  reflectable:
      path: /Volumes/DataElCapitan/SubSystem/Downloads/reflectable-use_build/reflectable
    #'^1.0.0'

transformers:
- dart_to_js_script_rewriter

#- reflectable:
#    entry_points:
#      - web/main.dart # The path to your main file
#    # formatted: true # Optional.
#

#web:
#  compiler:
#    debug: dartdevc
